---
- name: Create APT repo file (Debian)
  apt_repository:
    repo: "deb http://packages.cloud.google.com/apt {{ ansible_distribution_release }} main"
    state: present
    filename: google-cloud-sdk

- name: Import the APT key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

